"""empty message

Revision ID: b3b843e2edf9
Revises: 
Create Date: 2024-09-30 17:15:28.886163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b843e2edf9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('send_message', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('remaining_message', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('remaining_message')
        batch_op.drop_column('send_message')

    # ### end Alembic commands ###
